### ISSUE TITLE
How to pass arguments to mapper/reducer?

### ISSUE THREAD

**Issue by gglanzani** [basho/riak-python-client#396]
I'm trying to pass some arguments to a mapper. 

With the Riak client I trivially do it with the snippet `erlang-shell` in [this gist](https://gist.github.com/gglanzani/de14420a609dfbea04bd)

The problem is how to achieve the same with Python. In the same gist as above, I have the snippets `python-{first,second}-try` and `python-first-fail` which is the traceback. 

In the gist I've also included the Erlang code (sorry if it's ugly, it's my first Erlang week).

Am I doing something wrong? I couldn't find much in the documentation.

**Comment by javajolt** [comment]
@gglanzani It looks like you are passing in the `options` dict with a key of `args` instead of `arg`.  See if that works any better for you.  I think we should make the values to `options` a bit clearer in the documentation.

http://basho.github.io/riak-python-client/query.html#riak.mapreduce.RiakMapReduce.map

**Comment by gglanzani** [comment]
@javajolt Yes, you are right, sorry for the inconvenience. As an aside: I still don't get the results because of #394 :)

Regarding the docs: I think the could use some love too. A working MR example would be appreciated by the audience.

Keep up the good work!

**Comment by javajolt** [comment]
@lucperkins Your fans would love more M/R examples. Do we have something more detailed? Or are there plans to add other language examples to http://docs.basho.com/riak/latest/dev/using/mapreduce/?
