### ISSUE TITLE
Multi-get performance concerns [JIRA: CLIENTS-662]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak-python-client#417]
This is to do work benchmarking multi-get to ensure that it performs better than serial gets.

* Test using regular KV objects
* Test using CRDT objects

**Comment by lukebakken** [comment]
Paging @wesc :smile:

**Comment by lukebakken** [comment]
The Python client [includes benchmarking code for multiget](https://github.com/basho/riak-python-client/blob/master/riak/client/multiget.py#L205-L241). I have run this benchmark on my VM using the following scenarios:

* 1 cpu, 1 thread
* 4 cpus, 4 threads
* 1 cpu, 4 threads

In the 4 cpu / 4 thread case, multiget took half the time of sequential get.

@wesc could you please clone this repository and run the benchmark? Here's how I did it:

```
git clone git://github.com/basho/riak-python-client.git
cd riak-python-client
PYTHONPATH='.' python riak/client/multiget.py
```
The benchmark will connect to Riak running on `localhost`, using PB port `8087` and HTTP port `8098`. If you want to run the benchmark from another computer or connect to multiple nodes, you can modify [this line](https://github.com/basho/riak-python-client/blob/master/riak/client/multiget.py#L209) to use the same connection settings that your application uses.

**Comment by pigmej** [comment]
> In the 4 cpu / 4 thread case, multiget took half the time of sequential get.

First of all, cpython has GIL, adding cpu cores solves nothing in python world :) (as long as you don't release GIL in C extension).

Having parallel get is certainly faster than sequential get. You can also easily test it with gevent (remember to patch), and you will see that with pb it's waaaaaaaay faster than fetching everything in linear way.

Obviously as long as you don't run too much in parallel then riak and OS starts to choke.

**Comment by lukebakken** [comment]
Hi @pigmej -

I tried monkey-patching the python client with `gevent` to see if it made a difference in the benchmarks in `riak/client/multiget.py` and found that it did not. If you have observed something different please provide information, I would appreciate it.

As I observed earlier today, the only case where multi get was faster than sequential is when my VM had multiple CPUs.

**Comment by wesc** [comment]
I'll run the benchmark soon, but first a couple comments.

Python releases the GIL when making networking calls via the built in socket module. So you *should* see an improvement in a *network-bound* environment with 1 CPU and multiple threads. I'm inferring from your last comment that this is not the case? So that's odd, unless the benchmark is pegging the CPU.

Also, using 4 CPUs for a 2x gain seems... problematic? This means we'd get better overall throughput with one process per CPU, each making sequential gets. It doesn't smell right to me that multiget overhead might eat away half the performance.

`gevent` uses up a significant amount of CPU compared to regular Python networking, but that only starts to show at extreme network load. Unfortunately I don't have a citation for this and I don't think it's well known. We discovered it while working on services that make networking calls on the order of 10k - 20k round trips per second, where a monkey patched benchmark on a single core started underperforming the same un-monkeyed application.

**Comment by lukebakken** [comment]
I'll be interested to see what your benchmark runs show, and if you have comments about the benchmarking code itself.

**Comment by lukebakken** [comment]
Using `gevent` monkey patching significantly speeds up multi get and multi put. That will be the recommended fix until the client can be refactored.

See #446

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
