### ISSUE TITLE
Problem with list-keys [JIRA: CLIENTS-1015]

### ISSUE THREAD

**Issue by datalemming** [basho/riak-python-client#498]
I have the following code:

```
stream = c.ts_stream_keys('EUClaptimes')
for key_list in stream:
   print key_list
# print stream

stream.close()
```

That gives the following error messages:
`Attribute error: ‘str’ object has no attribute ‘name'`

If I amend it to:
```
stream = c.ts_stream_keys('EUClaptimes')
# for key_list in stream:

 #  print key_list
print stream
stream.close()
```

I do get a stream object

The table name etc exists as I am using it elsewhere on my jupyter notebook.

**Comment by lukebakken** [comment]
Checking this now with Riak TS 1.4

**Comment by alexmoore** [comment]
Just ran into this too.  The documentation is wrong, and you'll need to pass a Table object in instead of a string for the table name:

```
table = riak.Table(c, 'EUClaptimes')

stream = c.ts_stream_keys(table1)
for key_list in stream:
    print key_list

stream.close()
```

Looks like [ts_stream_keys()](https://github.com/basho/riak-python-client/blob/master/riak/client/operations.py#L637) is the only one that is missing this check, it'll need the lines:

```
        t = table
        if isinstance(t, six.string_types):
            t = Table(self, table)
``` 

added to it.

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
