### ISSUE TITLE
Clarification needed: multiget - calling queue.task_done without ever calling queue.join() [JIRA: CLIENTS-1083]

### ISSUE THREAD

**Issue by finnci** [basho/riak-python-client#521]
As seen in the [documentation](https://docs.python.org/2/library/queue.html#Queue.Queue.task_done), task_done is only used/cared for when you might be doing a Queue.join() call (looking at the python source code confirms this also). Which is never seen within multi.py, however I do see multiple instances of the task_done call; [example](https://github.com/basho/riak-python-client/blob/f13f0df8a566f0002210cb76bb942e9db8c25ea4/riak/client/multi.py#L222).

Is there some other undocumented side-affect of calling task_done in each of these places? Or is this likely an artefact of some older feature/ port from another language?

I realise that calling task_done doesn't cause anything to break, and keeps the queue in a state with a "more correct" view of what tasks it has processed, but i'm wondering if it _is_ used for something unexpected.

**Comment by lukebakken** [comment]
We could add a `join()` call [at the end of this method](https://github.com/basho/riak-python-client/blob/master/riak/client/multi.py#L115-L122), but as we do wait on all workers it isn't strictly necessary.

So, like you point out, `task_done()` isn't necessary either, but has been there since the dawn of time.

If you would like to follow up, please feel free to re-open this issue. Thanks!

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
